import os
import re
from datetime import datetime
from pathlib import Path
from fpdf import FPDF

SAVE_DIR = Path.home() / "Downloads"

# Header bar colour (deep navy)
HEADER_R, HEADER_G, HEADER_B = 30, 58, 95
# Accent colour for section labels (warm gold)
ACCENT_R, ACCENT_G, ACCENT_B = 200, 169, 110


def _sanitize(text: str) -> str:
    """Strip Markdown and replace non-Latin-1 characters for built-in PDF fonts."""
    text = re.sub(r"```[\s\S]*?```", "[code block]", text)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.MULTILINE)
    text = re.sub(r"\*{1,3}([^*\n]+)\*{1,3}", r"\1", text)
    text = re.sub(r"_{1,3}([^_\n]+)_{1,3}", r"\1", text)
    text = re.sub(r"^\s*[-*+]\s+", "  - ", text, flags=re.MULTILINE)
    text = re.sub(r"\[([^\]]+)\]\([^\)]+\)", r"\1", text)
    replacements = {
        "’": "'", "‘": "'", "“": '"', "”": '"',
        "–": "-", "—": "--", "•": "-", "…": "...",
        "é": "e", "à": "a", "ñ": "n", "ü": "u",
    }
    for char, rep in replacements.items():
        text = text.replace(char, rep)
    return text.encode("latin-1", "replace").decode("latin-1")


class _PDF(FPDF):
    def header(self):
        self.set_fill_color(HEADER_R, HEADER_G, HEADER_B)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 14, "AI Educator  |  Learning Session", fill=True, align="C",
                  new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(4)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10,
                  f"Page {self.page_no()}  |  Generated by AI Educator  |  "
                  f"{datetime.now().strftime('%Y-%m-%d %H:%M')}",
                  align="C")


def _section_label(pdf: _PDF, label: str):
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(ACCENT_R, ACCENT_G, ACCENT_B)
    pdf.cell(0, 9, label, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)


def export_to_pdf(mode: str, chat_history: list[dict],
                  image_path: str = None, filename: str = None) -> str:
    """Generate a formatted PDF of the full conversation and return the saved file path."""
    SAVE_DIR.mkdir(exist_ok=True)

    pdf = _PDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Meta line
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 7,
             f"Date: {datetime.now().strftime('%B %d, %Y  %H:%M')}     Mode: {mode}",
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(5)

    # Iterate through conversation pairs
    i = 0
    exchange_num = 0
    while i < len(chat_history) - 1:
        if chat_history[i]["role"] == "user" and chat_history[i + 1]["role"] == "assistant":
            exchange_num += 1
            question = chat_history[i]["content"]
            answer   = chat_history[i + 1]["content"]

            label = "Question" if exchange_num == 1 else f"Follow-up {exchange_num - 1}"
            _section_label(pdf, label)
            pdf.set_font("Helvetica", "", 11)
            pdf.multi_cell(0, 7, _sanitize(question))
            pdf.ln(3)

            _section_label(pdf, "Answer")
            pdf.set_font("Helvetica", "", 11)
            pdf.multi_cell(0, 7, _sanitize(answer))
            pdf.ln(5)

            # Divider between exchanges (not after the last one)
            if i + 2 < len(chat_history):
                pdf.set_draw_color(220, 220, 220)
                pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
                pdf.ln(5)

            i += 2
        else:
            i += 1

    # Diagram on a new page
    if image_path and os.path.exists(image_path):
        pdf.add_page()
        _section_label(pdf, "Flow Diagram")
        pdf.ln(4)
        usable_width = pdf.w - pdf.l_margin - pdf.r_margin
        pdf.image(image_path, x=pdf.l_margin, w=usable_width)

    if not filename:
        filename = f"ai_educator_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    out_path = SAVE_DIR / filename
    pdf.output(str(out_path))
    return str(out_path)
